### ISSUE TITLE
Task is not complete yet while initializing EThree

### ISSUE THREAD

**Issue by 3llomi** [VirgilSecurity/demo-firebase-android#3]
i am trying to add e3Kit to my app which is linked to Firebase and i already deployed the required Firebase Cloud functions however when i try to initialize the sdk on Android i got the error `Task is not yet complete`

i think that we should firstly  addOnSuccessListener and get the token then after that we need to initialize the e3kit SDK maybe?

here is the code which i copied from the Documentation

```kotlin
  val tokenCallback =
                    object : OnGetTokenCallback {
                        override fun onGetToken(): String {
                            val data = FirebaseFunctions.getInstance()
                                    .getHttpsCallable("getVirgilJwt")
                                    .call()
                                    .result
                                    ?.data as Map<String, String>

                            return data["token"]!!
                        }
                    }

            val initializeListener =
                    object : OnResultListener<EThree> {
                        override fun onSuccess(result: EThree) {
                            // Init done!
                            // Save the eThree instance
                        }

                        override fun onError(throwable: Throwable) {
                           //Task is not yet complete error here
                        }
                    }

            EThree.initialize(this, tokenCallback).addCallback(initializeListener)
```
can you check it please?
Thanks!

**Comment by BavovnaIsTaken** [comment]
Hi, @3llomi !
Maybe something in firebase has changed. 
May I ask you to debug onGetToken function, and see whether it returns a valid token in the end? (you can check it's validity on jwt.io)
Code inside `onGetToken` function has to be synchronous, but your error message looks like something in `onGetToken` may by async and is not initialized by the moment it's used.

Thank you!

**Comment by 3llomi** [comment]
Hi @BuddahLD,  i can only get the token if i used `addOnSuccessListener` like this:
```kotlin
FirebaseFunctions.getInstance()
                .getHttpsCallable("getVirgilJwt")
                .call()
                .addOnSuccessListener {
                    val data = it?.data as? Map<String,String>
                    
                }
```

i tired to get it synchronously using latest  vesrion of Firebase Functions SDK 19.0.1 and also an older version 16.3.0 and i got the same exception `Task is not complete yet`

**Comment by BavovnaIsTaken** [comment]
I'm looking into it. I'll text you the result tomorrow

**Comment by BavovnaIsTaken** [comment]
May I ask you to try this code while I'm looking for grace solution:
```
val tokenTask = FirebaseFunctions.getInstance()
        .getHttpsCallable("getVirgilJwt")
        .call()

val result = Tasks.await(tokenTask).data as Map<String, String>

val token = result["token"] ?: error("token cannot be null")
```

**Comment by 3llomi** [comment]
@BuddahLD Thanks man it worked finally! 
shouldn't be a way that would be more efficient rather than wrap this code in a 'Normal thread' like using Coroutines for example?

**Comment by BavovnaIsTaken** [comment]
yes, coroutines are great way to implement it

**Comment by 3llomi** [comment]
Thanks @BuddahLD , i just wrapped it up with a Coroutine and now 'hopefully' everything is working perfectly!.
